#ifndef DEBUG_H_INCLUDED
#define DEBUG_H_INCLUDED

//#define DEBUG_READ_FILE
//#define DEBUG_WRITE_FILE
//#define DEBUG_FOLDER
//#define DEBUG_ARGS
//#define DEBUG_PARSE_PROPERTY
//#define DEBUG_PARSE_CONFIG_SECTION
//#define DEBUG_PARSE_LANGUAGE
//#define DEBUG_LANGUAGES_FOUND
//#define DEBUG_PARSERHELPER
#define DEBUG_SERVICE_START

#endif // DEBUG_H_INCLUDED
